name: mustard
channels:
  - pytorch
  - defaults
dependencies:
  - pip:
    - allennlp==0.9.0
    # Apex needs nvcc, which isn't provided by cudatoolkit below. So you need to run the following having
    # a regular CUDA installation of the same version as the cudatoolkit below, and a compatible version
    # of GCC for that CUDA version (e.g., GCC 7 for CUDA 10.0).
    - git+https://github.com/NVIDIA/apex@606c3dc --global-option="--cpp_ext" --global-option="--cuda_ext"
    - jsonlines==1.2.0
    - overrides==1.9
  - cudatoolkit=10.0
  - cudnn=7.6.0
  - ffmpeg=4.0
  - h5py=2.9.0
  - nltk=3.4.1
  - numpy=1.15.4
  - pillow=5.4.1
  - pip=19.3.1
  - python=3.7.4
  - pytorch=1.3.0
  - scikit-learn=0.21.1
  - torchvision=0.4.1
  - tqdm=4.31.1
